# Custom sign key
sign_salt: salt

debug: false

redis:
  host: localhost
  port: 6379
  db:   0

# Netease Cloud Music API Key
encrypt:
  e: >-
    e
  
  n: >-
    n
  
  nonce: >-
    nonce

# Google reCAPTCHA key
recaptcha:
  secret:  secret
  sitekey: sitekey
